import { ITrendsRecommendTweet } from '@/types/api';

export const StaticTrendsRecommend: Record<string, ITrendsRecommendTweet[]> = {
  '82c6ba13-4c10-4813-b59e-68a6c5ff9929': [
    {
      url: 'https://twitter.com/ajassy/status/1945505468727885866',
      author_name: 'Andy Jassy',
      author_url: 'https://twitter.com/ajassy',
      html: '<blockquote class="twitter-tweet"><p lang="en" dir="ltr">At today’s <a href="https://twitter.com/awscloud?ref_src=twsrc%5Etfw">@awscloud</a> Summit NYC, we unveiled a new Bedrock capability called AgentCore – a set of powerful building blocks that will change how you can deploy agents into production in a secure, scalable, and flexible way. <a href="https://t.co/WVzY30ieoP">https://t.co/WVzY30ieoP</a> <a href="https://t.co/nRmizWEmnB">pic.twitter.com/nRmizWEmnB</a></p>&mdash; Andy Jassy (@ajassy) <a href="https://twitter.com/ajassy/status/1945505468727885866?ref_src=twsrc%5Etfw">July 16, 2025</a></blockquote>',
      width: 550,
      height: null,
      type: 'rich',
      cache_age: '3153600000',
      provider_name: 'Twitter',
      provider_url: 'https://twitter.com',
      version: '1.0',
    },
    {
      url: 'https://twitter.com/labeveryday/status/1945505179421343968',
      author_name: "Du'An S. Lightfoot ☁️",
      author_url: 'https://twitter.com/labeveryday',
      html: '<blockquote class="twitter-tweet"><p lang="en" dir="ltr">I am loving the Agentic AI tools and resources we are building at AWS right now. <br><br>If you are building agents you will see that the Strands Agents SDK makes it easy and fast to get an agent or multi-agent solution up and running. <br><br>But where do you host it? How do you scale? And… <a href="https://t.co/tKEZDelOB1">pic.twitter.com/tKEZDelOB1</a></p>&mdash; Du&#39;An S. Lightfoot ☁️ (@labeveryday) <a href="https://twitter.com/labeveryday/status/1945505179421343968?ref_src=twsrc%5Etfw">July 16, 2025</a></blockquote>',
      width: 550,
      height: null,
      type: 'rich',
      cache_age: '3153600000',
      provider_name: 'Twitter',
      provider_url: 'https://twitter.com',
      version: '1.0',
    },
    {
      url: 'https://twitter.com/holgermu/status/1945579265568743902',
      author_name: 'Holger Müller #EnterpriseAcceleration',
      author_url: 'https://twitter.com/holgermu',
      html: '<blockquote class="twitter-tweet"><p lang="en" dir="ltr">And some key <a href="https://twitter.com/amazon?ref_src=twsrc%5Etfw">@Amazon</a> Bedrock Agentcore Runtime features. <br><br>- Industry-leading serverless performance with up to 8 hours extended runtime<br>- Checkpointing and recovery capabilities support graceful recovery<br>- Scale up to thousands of agent invocation sessions in just seconds<br>-… <a href="https://t.co/ioR8a9xagg">pic.twitter.com/ioR8a9xagg</a></p>&mdash; Holger Müller #EnterpriseAcceleration (@holgermu) <a href="https://twitter.com/holgermu/status/1945579265568743902?ref_src=twsrc%5Etfw">July 16, 2025</a></blockquote>',
      width: 550,
      height: null,
      type: 'rich',
      cache_age: '3153600000',
      provider_name: 'Twitter',
      provider_url: 'https://twitter.com',
      version: '1.0',
    },
    {
      url: 'https://twitter.com/EverymansAI/status/1947000307625402689',
      author_name: 'Everymans.ai',
      author_url: 'https://twitter.com/EverymansAI',
      html: '<blockquote class="twitter-tweet"><p lang="en" dir="ltr">👉 Agentic AI is evolving from hype to high-ROI reality 💥 Exciting week in agentic AI! From scalable platforms to dynamic frameworks, below is the latest on enterprise-ready announcements, use cases, new market entrants, and infrastructure updates reshaping autonomous AI… <a href="https://t.co/Dv9Iw9f6M2">pic.twitter.com/Dv9Iw9f6M2</a></p>&mdash; Everymans.ai (@EverymansAI) <a href="https://twitter.com/EverymansAI/status/1947000307625402689?ref_src=twsrc%5Etfw">July 20, 2025</a></blockquote>',
      width: 550,
      height: null,
      type: 'rich',
      cache_age: '3153600000',
      provider_name: 'Twitter',
      provider_url: 'https://twitter.com',
      version: '1.0',
    },
    {
      url: 'https://twitter.com/lizkmiller/status/1945507100508946717',
      author_name: 'Liz Miller',
      author_url: 'https://twitter.com/lizkmiller',
      html: '<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Next in the <a href="https://twitter.com/hashtag/AWSSummitNYC?src=hash&amp;ref_src=twsrc%5Etfw">#AWSSummitNYC</a> <a href="https://twitter.com/hashtag/News?src=hash&amp;ref_src=twsrc%5Etfw">#News</a> dump introducing <a href="https://twitter.com/hashtag/Amazon?src=hash&amp;ref_src=twsrc%5Etfw">#Amazon</a> Bedrock <a href="https://twitter.com/hashtag/AgentCore?src=hash&amp;ref_src=twsrc%5Etfw">#AgentCore</a> <br><br>&quot;This is a step change for moving your agents from <a href="https://twitter.com/hashtag/POC?src=hash&amp;ref_src=twsrc%5Etfw">#POC</a> to production with scale reliability and security that are critical to real world deployment.&quot; <a href="https://t.co/QtRo4cdJ73">pic.twitter.com/QtRo4cdJ73</a></p>&mdash; Liz Miller (@lizkmiller) <a href="https://twitter.com/lizkmiller/status/1945507100508946717?ref_src=twsrc%5Etfw">July 16, 2025</a></blockquote>',
      width: 550,
      height: null,
      type: 'rich',
      cache_age: '3153600000',
      provider_name: 'Twitter',
      provider_url: 'https://twitter.com',
      version: '1.0',
    },
    {
      url: 'https://twitter.com/awscloud/status/1945503927752941591',
      author_name: 'Amazon Web Services',
      author_url: 'https://twitter.com/awscloud',
      html: '<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Take the fast lane from prototype to production. 🛣️⚡️☁️<br><br>Introducing Amazon Bedrock AgentCore, fully-managed services to deploy &amp; operate capable AI agents securely, at scale. Accelerate your development using any framework &amp; any model.<br><br>👉 <a href="https://t.co/YLT8CRqIWf">https://t.co/YLT8CRqIWf</a> <a href="https://t.co/ke6e5eI11X">pic.twitter.com/ke6e5eI11X</a></p>&mdash; Amazon Web Services (@awscloud) <a href="https://twitter.com/awscloud/status/1945503927752941591?ref_src=twsrc%5Etfw">July 16, 2025</a></blockquote>',
      width: 550,
      height: null,
      type: 'rich',
      cache_age: '3153600000',
      provider_name: 'Twitter',
      provider_url: 'https://twitter.com',
      version: '1.0',
    },
  ],
  'ed83caf9-b958-4cb1-82ff-d02d1c67c89c': [
    {
      url: 'https://twitter.com/KryptonAi/status/1947227274257764776',
      author_name: 'I am AI',
      author_url: 'https://twitter.com/KryptonAi',
      html: '<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Meta just walked away from the EU’s voluntary <a href="https://twitter.com/hashtag/AI?src=hash&amp;ref_src=twsrc%5Etfw">#AI</a> code of practice, calling it a legal grey zone that stretches beyond the coming AI Act. For a platform shipping Llama to millions of devs, that’s a bold way to say “wait for the law.” 🤔<br><br>Microsoft signals it will sign, betting… <a href="https://t.co/njYjZa0vQK">pic.twitter.com/njYjZa0vQK</a></p>&mdash; I am AI (@KryptonAi) <a href="https://twitter.com/KryptonAi/status/1947227274257764776?ref_src=twsrc%5Etfw">July 21, 2025</a></blockquote>',
      width: 550,
      height: null,
      type: 'rich',
      cache_age: '3153600000',
      provider_name: 'Twitter',
      provider_url: 'https://twitter.com',
      version: '1.0',
    },
    {
      url: 'https://twitter.com/LuizaJarovsky/status/1946245030093693436',
      author_name: 'Luiza Jarovsky, PhD',
      author_url: 'https://twitter.com/LuizaJarovsky',
      html: '<blockquote class="twitter-tweet"><p lang="en" dir="ltr">🚨 BREAKING: Meta defies the EU and says it WON&#39;T sign the EU AI Act&#39;s Code of Practice for general-purpose AI models. 😱 Here&#39;s what its Chief Global Affairs Officer said:<br><br>&quot;Europe is heading down the wrong path on AI. We have carefully reviewed the European Commission’s Code of… <a href="https://t.co/Ph8OKiNNAX">pic.twitter.com/Ph8OKiNNAX</a></p>&mdash; Luiza Jarovsky, PhD (@LuizaJarovsky) <a href="https://twitter.com/LuizaJarovsky/status/1946245030093693436?ref_src=twsrc%5Etfw">July 18, 2025</a></blockquote>',
      width: 550,
      height: null,
      type: 'rich',
      cache_age: '3153600000',
      provider_name: 'Twitter',
      provider_url: 'https://twitter.com',
      version: '1.0',
    },
    {
      url: 'https://twitter.com/thetechfinhq/status/1946325482888110296',
      author_name: 'TheTechFin',
      author_url: 'https://twitter.com/thetechfinhq',
      html: '<blockquote class="twitter-tweet"><p lang="en" dir="ltr">⚖️ Meta Rejects EU AI Code of Practice, Citing Legal Concerns and Overreach 🚫🤖<br><br>Meta has officially refused to sign the European Union’s voluntary AI Code of Practice, just weeks before the EU’s AI Act is set to take effect. The framework is meant to guide companies in… <a href="https://t.co/OpCfqnsHDF">pic.twitter.com/OpCfqnsHDF</a></p>&mdash; TheTechFin (@thetechfinhq) <a href="https://twitter.com/thetechfinhq/status/1946325482888110296?ref_src=twsrc%5Etfw">July 18, 2025</a></blockquote>',
      width: 550,
      height: null,
      type: 'rich',
      cache_age: '3153600000',
      provider_name: 'Twitter',
      provider_url: 'https://twitter.com',
      version: '1.0',
    },
    {
      url: 'https://twitter.com/POLITICOEurope/status/1946203736763769273',
      author_name: 'POLITICOEurope',
      author_url: 'https://twitter.com/POLITICOEurope',
      html: '<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Meta just blew a hole in a EU plan to tame artificial intelligence models.<br><br>Today, the technology giant  was the first Big Tech company to come out saying it will not sign the EU&#39;s code of practice for general-purpose AI.<a href="https://t.co/1kVb7I60kP">https://t.co/1kVb7I60kP</a></p>&mdash; POLITICOEurope (@POLITICOEurope) <a href="https://twitter.com/POLITICOEurope/status/1946203736763769273?ref_src=twsrc%5Etfw">July 18, 2025</a></blockquote>',
      width: 550,
      height: null,
      type: 'rich',
      cache_age: '3153600000',
      provider_name: 'Twitter',
      provider_url: 'https://twitter.com',
      version: '1.0',
    },
    {
      url: 'https://twitter.com/JCtechfuture/status/1945081048397742499',
      author_name: 'zibar.eth | Token2049 | Web3 BuildΞr | Futurist',
      author_url: 'https://twitter.com/JCtechfuture',
      html: '<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Interesting and arguably useful framework however one has to question how many innovative fast-moving AI centric companies will sign up and comply.   Those solely targeting EU, sure but others with a global vision - - - unlikely IMHO.  The rigidity and transparency &lt;if that&#39;s… <a href="https://t.co/mtLi989NB8">pic.twitter.com/mtLi989NB8</a></p>&mdash; zibar.eth | Token2049 | Web3 BuildΞr | Futurist (@JCtechfuture) <a href="https://twitter.com/JCtechfuture/status/1945081048397742499?ref_src=twsrc%5Etfw">July 15, 2025</a></blockquote>',
      width: 550,
      height: null,
      type: 'rich',
      cache_age: '3153600000',
      provider_name: 'Twitter',
      provider_url: 'https://twitter.com',
      version: '1.0',
    },
    {
      url: 'https://twitter.com/Forbes_MENA_/status/1946306068981727590',
      author_name: 'Forbes Middle East',
      author_url: 'https://twitter.com/Forbes_MENA_',
      html: '<blockquote class="twitter-tweet"><p lang="en" dir="ltr"><a href="https://twitter.com/hashtag/Meta?src=hash&amp;ref_src=twsrc%5Etfw">#Meta</a> has refused to sign the <a href="https://twitter.com/hashtag/EU?src=hash&amp;ref_src=twsrc%5Etfw">#EU</a>&#39;s AI code of practice, arguing that the framework represents regulatory overreach that could harm innovation and limit technology growth.<a href="https://twitter.com/hashtag/Forbes?src=hash&amp;ref_src=twsrc%5Etfw">#Forbes</a> <br><br>For more details: 🔗 <a href="https://t.co/EkWqUc7hAD">https://t.co/EkWqUc7hAD</a> <a href="https://t.co/VhlUfQ8jIv">pic.twitter.com/VhlUfQ8jIv</a></p>&mdash; Forbes Middle East (@Forbes_MENA_) <a href="https://twitter.com/Forbes_MENA_/status/1946306068981727590?ref_src=twsrc%5Etfw">July 18, 2025</a></blockquote>',
      width: 550,
      height: null,
      type: 'rich',
      cache_age: '3153600000',
      provider_name: 'Twitter',
      provider_url: 'https://twitter.com',
      version: '1.0',
    },
  ],
  'cc8fe63e-ee48-4b0c-ab9d-2fa4ad8c93c0': [
    {
      url: 'https://twitter.com/cb_doge/status/1938966875897233741',
      author_name: 'DogeDesigner',
      author_url: 'https://twitter.com/cb_doge',
      html: '<blockquote class="twitter-tweet"><p lang="en" dir="ltr">BREAKING: Elon Musk confirms Grok 4 just achieved its best real-world results yet. Last night’s big model run, tested with xAI’s command line editor, delivered the most useful AI outputs to date. Release expected in the next two weeks. <a href="https://t.co/pSY3SuDxdp">pic.twitter.com/pSY3SuDxdp</a></p>&mdash; DogeDesigner (@cb_doge) <a href="https://twitter.com/cb_doge/status/1938966875897233741?ref_src=twsrc%5Etfw">June 28, 2025</a></blockquote>',
      width: 550,
      height: null,
      type: 'rich',
      cache_age: '3153600000',
      provider_name: 'Twitter',
      provider_url: 'https://twitter.com',
      version: '1.0',
    },
    {
      url: 'https://twitter.com/MarioNawfal/status/1943244433262051403',
      author_name: 'Mario Nawfal',
      author_url: 'https://twitter.com/MarioNawfal',
      html: '<blockquote class="twitter-tweet"><p lang="en" dir="ltr">GROK 4: FROM UNDERDOG TO WORLD LEADER<br><br>In 2023, Elon founded xAI with a mission to build an AI focused on truth, transparency, and understanding the universe.<br><br>Fast forward 16 months, and Grok 4 is sitting alone at the top of the AI intelligence charts, outscoring GPT-4, Claude… <a href="https://t.co/fmroy3SzdL">https://t.co/fmroy3SzdL</a> <a href="https://t.co/ISLccjvx3q">pic.twitter.com/ISLccjvx3q</a></p>&mdash; Mario Nawfal (@MarioNawfal) <a href="https://twitter.com/MarioNawfal/status/1943244433262051403?ref_src=twsrc%5Etfw">July 10, 2025</a></blockquote>',
      width: 550,
      height: null,
      type: 'rich',
      cache_age: '3153600000',
      provider_name: 'Twitter',
      provider_url: 'https://twitter.com',
      version: '1.0',
    },
    {
      url: 'https://twitter.com/JvShah124/status/1943247036192591875',
      author_name: 'JV Shah',
      author_url: 'https://twitter.com/JvShah124',
      html: '<blockquote class="twitter-tweet"><p lang="en" dir="ltr">🚨 BREAKING: Grok 4 is officially here.<br><br>Elon Musk just dropped the latest version of xAI’s chatbot and it&#39;s their most powerful model yet.<br><br>Here’s everything you need to know about Grok 4 (features, benchmarks, controversy): 🧵👇 <a href="https://t.co/ow2iLzxPza">pic.twitter.com/ow2iLzxPza</a></p>&mdash; JV Shah (@JvShah124) <a href="https://twitter.com/JvShah124/status/1943247036192591875?ref_src=twsrc%5Etfw">July 10, 2025</a></blockquote>',
      width: 550,
      height: null,
      type: 'rich',
      cache_age: '3153600000',
      provider_name: 'Twitter',
      provider_url: 'https://twitter.com',
      version: '1.0',
    },
    {
      url: 'https://twitter.com/web3nity/status/1945920058749763667',
      author_name: 'Webtrinity',
      author_url: 'https://twitter.com/web3nity',
      html: '<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Grok 4 by xAI is out. Elon Musk’s new AI – there’s a lot of discussion around it right now.<br>But what’s actually important about it, beyond the flashy headlines?<br>Here’s a quick breakdown of what really matters about Grok 4 👇 <a href="https://t.co/ze0gk63l6d">pic.twitter.com/ze0gk63l6d</a></p>&mdash; Webtrinity (@web3nity) <a href="https://twitter.com/web3nity/status/1945920058749763667?ref_src=twsrc%5Etfw">July 17, 2025</a></blockquote>',
      width: 550,
      height: null,
      type: 'rich',
      cache_age: '3153600000',
      provider_name: 'Twitter',
      provider_url: 'https://twitter.com',
      version: '1.0',
    },
    {
      url: 'https://twitter.com/amXFreeze/status/1944697268327551244',
      author_name: 'X Freeze',
      author_url: 'https://twitter.com/amXFreeze',
      html: '<blockquote class="twitter-tweet"><p lang="en" dir="ltr">🚨 Update: GROK 4.20 is releasing soon<br><br>Right Elon just confirmed that Grok V7 foundation model is being trained... (GROK 4 is V6)<br><br>This time xAI has more control over training data and specifically hand picked to filter out the woke dump yard.. <br><br>It will be extremely good at… <a href="https://t.co/G1KgL060cA">pic.twitter.com/G1KgL060cA</a></p>&mdash; X Freeze (@amXFreeze) <a href="https://twitter.com/amXFreeze/status/1944697268327551244?ref_src=twsrc%5Etfw">July 14, 2025</a></blockquote>',
      width: 550,
      height: null,
      type: 'rich',
      cache_age: '3153600000',
      provider_name: 'Twitter',
      provider_url: 'https://twitter.com',
      version: '1.0',
    },
    {
      url: 'https://twitter.com/iam_smx/status/1938564920267645020',
      author_name: 'SMX 🇺🇸',
      author_url: 'https://twitter.com/iam_smx',
      html: '<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Elon Musk is in Founder Mode, locked in! 🔥<br><br>He just revealed he’s still at work till now, grinding with the <a href="https://twitter.com/xai?ref_src=twsrc%5Etfw">@xAI</a> team on <a href="https://twitter.com/grok?ref_src=twsrc%5Etfw">@Grok</a>, as we speak, Grok 4 is almost here.<br><br>Just one final big run left, the specialized coding model is coming soon. Launch expected right after July 4th. <a href="https://t.co/yIq5NPFZcN">pic.twitter.com/yIq5NPFZcN</a></p>&mdash; SMX 🇺🇸 (@iam_smx) <a href="https://twitter.com/iam_smx/status/1938564920267645020?ref_src=twsrc%5Etfw">June 27, 2025</a></blockquote>',
      width: 550,
      height: null,
      type: 'rich',
      cache_age: '3153600000',
      provider_name: 'Twitter',
      provider_url: 'https://twitter.com',
      version: '1.0',
    },
  ],
  '9f6e6a51-2fd1-4a4d-86fc-b07a27c46815': [
    {
      url: 'https://twitter.com/StockSavvyShay/status/1883167673326178426',
      author_name: 'Shay Boloor',
      author_url: 'https://twitter.com/StockSavvyShay',
      html: '<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Energy is the biggest bottleneck for AI data centers &amp; meeting future demand will require innovative solutions to overcome infrastructure limits -- these are the key beneficiaries 🧐<br><br>• <a href="https://twitter.com/search?q=%24TSLA&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$TSLA</a> -- Revolutionizing data center energy storage<br>• <a href="https://twitter.com/search?q=%24FSLR&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$FSLR</a> -- Solar energy solutions for… <a href="https://t.co/BtvRHNea6g">pic.twitter.com/BtvRHNea6g</a></p>&mdash; Shay Boloor (@StockSavvyShay) <a href="https://twitter.com/StockSavvyShay/status/1883167673326178426?ref_src=twsrc%5Etfw">January 25, 2025</a></blockquote>',
      width: 550,
      height: null,
      type: 'rich',
      cache_age: '3153600000',
      provider_name: 'Twitter',
      provider_url: 'https://twitter.com',
      version: '1.0',
    },
    {
      url: 'https://twitter.com/Umbisam/status/1937910118252712411',
      author_name: '𝒰𝓂𝒷𝒾𝓈𝒶𝓂',
      author_url: 'https://twitter.com/Umbisam',
      html: '<blockquote class="twitter-tweet"><p lang="en" dir="ltr"><a href="https://twitter.com/search?q=%24IREN&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$IREN</a> Can US Infrastructure Keep Up with The AI Economy ? Nope Is The Correct Answer.<br><br>The scale of AI data centers and their commensurate power needs are growing exponentially. By 2035, Deloitte estimates that power demand from AI data centers in the United States could grow… <a href="https://t.co/JUQtguyvIH">pic.twitter.com/JUQtguyvIH</a></p>&mdash; 𝒰𝓂𝒷𝒾𝓈𝒶𝓂 (@Umbisam) <a href="https://twitter.com/Umbisam/status/1937910118252712411?ref_src=twsrc%5Etfw">June 25, 2025</a></blockquote>',
      width: 550,
      height: null,
      type: 'rich',
      cache_age: '3153600000',
      provider_name: 'Twitter',
      provider_url: 'https://twitter.com',
      version: '1.0',
    },
    {
      url: 'https://twitter.com/StockSavvyShay/status/1903401854966604081',
      author_name: 'Shay Boloor',
      author_url: 'https://twitter.com/StockSavvyShay',
      html: '<blockquote class="twitter-tweet"><p lang="en" dir="ltr">THE ULTIMATE CHEAT SHEET FOR SOLVING THE AI ENERGY BOTTLENECK<br><br>• <a href="https://twitter.com/search?q=%24TSLA&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$TSLA</a> -- Revolutionizing data center energy storage<br>• <a href="https://twitter.com/search?q=%24FSLR&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$FSLR</a> -- Solar energy solutions for hyperscale data centers<br>• <a href="https://twitter.com/search?q=%24CCJ&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$CCJ</a> -- Supplying uranium for next-generation nuclear data centers<br>• <a href="https://twitter.com/search?q=%24CEG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$CEG</a> -- Delivering… <a href="https://t.co/egzQci11FW">pic.twitter.com/egzQci11FW</a></p>&mdash; Shay Boloor (@StockSavvyShay) <a href="https://twitter.com/StockSavvyShay/status/1903401854966604081?ref_src=twsrc%5Etfw">March 22, 2025</a></blockquote>',
      width: 550,
      height: null,
      type: 'rich',
      cache_age: '3153600000',
      provider_name: 'Twitter',
      provider_url: 'https://twitter.com',
      version: '1.0',
    },
    {
      url: 'https://twitter.com/MarioNawfal/status/1921261705398476896',
      author_name: 'Mario Nawfal',
      author_url: 'https://twitter.com/MarioNawfal',
      html: '<blockquote class="twitter-tweet"><p lang="en" dir="ltr">🚨 AI BOOM IS SUCKING WATER FROM DROUGHT-PRONE AREAS<br><br>Every time you ask AI to write an essay or make a meme, it sends a request to a data center — giant buildings full of computers that guzzle water to stay cool.<br><br>Since 2022, 160+ new AI data centers were built in parts of the… <a href="https://t.co/z0S6nuX7Dq">pic.twitter.com/z0S6nuX7Dq</a></p>&mdash; Mario Nawfal (@MarioNawfal) <a href="https://twitter.com/MarioNawfal/status/1921261705398476896?ref_src=twsrc%5Etfw">May 10, 2025</a></blockquote>',
      width: 550,
      height: null,
      type: 'rich',
      cache_age: '3153600000',
      provider_name: 'Twitter',
      provider_url: 'https://twitter.com',
      version: '1.0',
    },
    {
      url: 'https://twitter.com/SaanyaOjha/status/1945159084648620266',
      author_name: 'Saanya Ojha',
      author_url: 'https://twitter.com/SaanyaOjha',
      html: '<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Meta has hit Command + Zuck on its AI strategy - shredding the open-source playbook and replacing it with one that reads: Compute. Talent. Secrecy. The vibe is no longer “open source for all.” It’s “closed doors, infinite compute, elite team, existential stakes.” Let&#39;s break it… <a href="https://t.co/KvxhyIZSY2">pic.twitter.com/KvxhyIZSY2</a></p>&mdash; Saanya Ojha (@SaanyaOjha) <a href="https://twitter.com/SaanyaOjha/status/1945159084648620266?ref_src=twsrc%5Etfw">July 15, 2025</a></blockquote>',
      width: 550,
      height: null,
      type: 'rich',
      cache_age: '3153600000',
      provider_name: 'Twitter',
      provider_url: 'https://twitter.com',
      version: '1.0',
    },
    {
      url: 'https://twitter.com/MarioNawfal/status/1941467103888015697',
      author_name: 'Mario Nawfal',
      author_url: 'https://twitter.com/MarioNawfal',
      html: '<blockquote class="twitter-tweet"><p lang="en" dir="ltr">🚨🇺🇸 AI’S POWER HUNGER REVIVES NUCLEAR PLANTS ACROSS THE U.S.<br><br>America’s data centers are set to devour so much electricity in the next five years they’ll rival Japan’s entire power use today, forcing Big Tech into bed with nuclear energy to keep the lights - and servers - on.… <a href="https://t.co/pnDjBBtT3g">https://t.co/pnDjBBtT3g</a> <a href="https://t.co/QOYFXdqJoN">pic.twitter.com/QOYFXdqJoN</a></p>&mdash; Mario Nawfal (@MarioNawfal) <a href="https://twitter.com/MarioNawfal/status/1941467103888015697?ref_src=twsrc%5Etfw">July 5, 2025</a></blockquote>',
      width: 550,
      height: null,
      type: 'rich',
      cache_age: '3153600000',
      provider_name: 'Twitter',
      provider_url: 'https://twitter.com',
      version: '1.0',
    },
  ],
  '7f913d38-e464-4469-98d4-146c1ab59203': [
    {
      url: 'https://twitter.com/OpenAI/status/1945904743148323285',
      author_name: 'OpenAI',
      author_url: 'https://twitter.com/OpenAI',
      html: '<blockquote class="twitter-tweet"><p lang="en" dir="ltr">ChatGPT can now do work for you using its own computer.<br><br>Introducing ChatGPT agent—a unified agentic system combining Operator’s action-taking remote browser, deep research’s web synthesis, and ChatGPT’s conversational strengths. <a href="https://t.co/7uN2Nc6nBQ">pic.twitter.com/7uN2Nc6nBQ</a></p>&mdash; OpenAI (@OpenAI) <a href="https://twitter.com/OpenAI/status/1945904743148323285?ref_src=twsrc%5Etfw">July 17, 2025</a></blockquote>',
      width: 550,
      height: null,
      type: 'rich',
      cache_age: '3153600000',
      provider_name: 'Twitter',
      provider_url: 'https://twitter.com',
      version: '1.0',
    },
    {
      url: 'https://twitter.com/_K_Stiles/status/1946298936970576315',
      author_name: 'Katherine Stiles',
      author_url: 'https://twitter.com/_K_Stiles',
      html: '<blockquote class="twitter-tweet"><p lang="en" dir="ltr">OpenAI launches agentic AI that brings additional and novel risk… <a href="https://t.co/JldrerCq3f">pic.twitter.com/JldrerCq3f</a></p>&mdash; Katherine Stiles (@_K_Stiles) <a href="https://twitter.com/_K_Stiles/status/1946298936970576315?ref_src=twsrc%5Etfw">July 18, 2025</a></blockquote>',
      width: 550,
      height: null,
      type: 'rich',
      cache_age: '3153600000',
      provider_name: 'Twitter',
      provider_url: 'https://twitter.com',
      version: '1.0',
    },
    {
      url: 'https://twitter.com/Activewurld_/status/1946166207335268815',
      author_name: 'Activewurld',
      author_url: 'https://twitter.com/Activewurld_',
      html: '<blockquote class="twitter-tweet"><p lang="en" dir="ltr">OpenAI has officially unveiled its most advanced feature yet: ChatGPT Agent, a powerful tool that goes beyond simple chatbot conversations to actually control a virtual computer and perform complex tasks on your behalf. <br><br>This marks a major leap in how we interact with AI,… <a href="https://t.co/7e54i7MXTU">pic.twitter.com/7e54i7MXTU</a></p>&mdash; Activewurld (@Activewurld_) <a href="https://twitter.com/Activewurld_/status/1946166207335268815?ref_src=twsrc%5Etfw">July 18, 2025</a></blockquote>',
      width: 550,
      height: null,
      type: 'rich',
      cache_age: '3153600000',
      provider_name: 'Twitter',
      provider_url: 'https://twitter.com',
      version: '1.0',
    },
    {
      url: 'https://twitter.com/TechnicalNewsHQ/status/1946646629580513415',
      author_name: 'Tech News',
      author_url: 'https://twitter.com/TechnicalNewsHQ',
      html: '<blockquote class="twitter-tweet"><p lang="en" dir="ltr">OpenAI has just launched its most powerful tool yet: the ChatGPT Agent, now available for ChatGPT Pro, Plus, and Team users. This next-generation AI assistant doesn’t just answer questions-it completes work for you using its own virtual computer and a purpose-built, advanced… <a href="https://t.co/SYIRzB8y7S">pic.twitter.com/SYIRzB8y7S</a></p>&mdash; Tech News (@TechnicalNewsHQ) <a href="https://twitter.com/TechnicalNewsHQ/status/1946646629580513415?ref_src=twsrc%5Etfw">July 19, 2025</a></blockquote>',
      width: 550,
      height: null,
      type: 'rich',
      cache_age: '3153600000',
      provider_name: 'Twitter',
      provider_url: 'https://twitter.com',
      version: '1.0',
    },
    {
      url: 'https://twitter.com/abhishek/status/1945912881301626985',
      author_name: 'Abhishek Bhatnagar',
      author_url: 'https://twitter.com/abhishek',
      html: '<blockquote class="twitter-tweet"><p lang="en" dir="ltr">🚨 Latest AI News from OpenAI 🚨<br><br>🧵 OpenAI just introduced ChatGPT Agent, an AI assistant that doesn’t just chat—it acts 💥 <br><br>It can autonomously use a virtual computer: browsing, clicking, typing—all with your go‑ahead <a href="https://t.co/ETiwW5akOW">pic.twitter.com/ETiwW5akOW</a></p>&mdash; Abhishek Bhatnagar (@abhishek) <a href="https://twitter.com/abhishek/status/1945912881301626985?ref_src=twsrc%5Etfw">July 17, 2025</a></blockquote>',
      width: 550,
      height: null,
      type: 'rich',
      cache_age: '3153600000',
      provider_name: 'Twitter',
      provider_url: 'https://twitter.com',
      version: '1.0',
    },
    {
      url: 'https://twitter.com/briansolis/status/1945925690785951962',
      author_name: 'Brian Solis',
      author_url: 'https://twitter.com/briansolis',
      html: '<blockquote class="twitter-tweet"><p lang="en" dir="ltr">🚨OpenAI just launched ChatGPT Agent (also called “Agent Mode”).<br><br>This new AI combines the capabilities of its earlier tools (Operator and Deep Research) into a unified agentic system that functions like a &quot;virtual computer.&quot;<br><br>Agent enables complex, multi-step workflows such as… <a href="https://t.co/0dmC4ao9CI">pic.twitter.com/0dmC4ao9CI</a></p>&mdash; Brian Solis (@briansolis) <a href="https://twitter.com/briansolis/status/1945925690785951962?ref_src=twsrc%5Etfw">July 17, 2025</a></blockquote>',
      width: 550,
      height: null,
      type: 'rich',
      cache_age: '3153600000',
      provider_name: 'Twitter',
      provider_url: 'https://twitter.com',
      version: '1.0',
    },
  ],
};
